Repository openwebwork/pg, pull requests merged in 2021-03, with the labels that each got.

#540 Correct typo in context property. (#536)
  macros/contextPiecewiseFunction.pl
Labels: MathObject issue

#538 Do a typecheck before comparing functions. (bugzilla bug 4559)
  lib/Value/AnswerChecker.pm
Labels: MathObject issue, needs testing, priority 1

#537 Follow alias chain, not just first alias. (#518)
  lib/Parser/String.pm
  lib/Value/Context/Data.pm
Labels: MathObject issue, needs testing, priority2

#532 Update WeBWorK to use MathJax version 3.
  macros/PG.pl
  macros/PGbasicmacros.pl
  macros/parserGraphTool.pl
Labels: Put comment in release notes, needs testing, priority 1

#529 Switch from opening a new window to opening a dialog when an image is clicked
  macros/PGbasicmacros.pl
Labels: essentially ready to merge

#489 Fix applets in gateway quizzes
  lib/Applet.pm
  lib/PGcore.pm
  macros/AppletObjects.pl
  macros/PG.pl
Labels: Put comment in release notes, essentially ready to merge, needs testing

#522 Fix some issues with the sage.pl macro.
  macros/sage.pl
Labels: essentially ready to merge, priority2 (moderate)

#541 Add options to add TeX libraries and add to the TeX preamble in the PGtikz.pl macro
  lib/TikZImage.pm
  macros/PGtikz.pl
Labels: Put comment in release notes, essentially ready to merge, priority 1 (high)

#487 Make function parenPrecedence greater than unary negative, postive
  lib/Parser/Context/Default.pm
Labels: MathObject issue, essentially ready to merge, priority2 (moderate)

#539 Adjust the default class for [...] and {...}, and do type-matching in list comparisons. (#535)
  lib/Parser/Context/Default.pm
  lib/Value/AnswerChecker.pm
Labels: MathObject issue, essentially ready to merge, needs testing, priority2 (moderate)

#441 'digits' tolType
  lib/Value.pm
  lib/Value/Real.pm
Labels: MathObject issue, priority2 (moderate)

#544 Make PGML work for hardcopy if used in a set header file
  macros/PGML.pl
  macros/PGbasicmacros.pl
Labels: Do Not Merge Yet, Enhancement, priority 1 (high)

#549 Update the AppletObjects.pl macro for changes in the ADD_JS_FILE usage
  macros/AppletObjects.pl
  macros/PG.pl
Labels: priority2 (moderate)
