Repository openwebwork/pg, pull requests merged in 2021-04, with the labels that each got.

#559 alt option for image()
  macros/PGbasicmacros.pl
Labels: priority2 (moderate)

#561 direct use of WWPlot or TikZImage objects in image()
  macros/PGbasicmacros.pl
Labels: Put comment in release notes

#556 Fix POD generation errors.
  doc/MathObjects/README.pod
  lib/PGcore.pm
  lib/Value/AnswerChecker.pm
  lib/Value/Matrix.pm
  lib/WeBWorK/EquationCache.pm
  macros/AppletObjects.pl
  macros/LinearProgramming.pl
  macros/MatrixReduce.pl
  macros/PG.pl
  macros/PGessaymacros.pl
  macros/PGmorematrixmacros.pl
  macros/contextCongruence.pl
  macros/extraAnswerEvaluators.pl
  macros/niceTables.pl
  macros/source.pl
  macros/tableau.pl
  macros/unionLists.pl
  macros/unionTables.pl
  macros/weightedGrader.pl
Labels: priority2 (moderate)

#550 updated version
  VERSION
Labels: Do Not Merge Yet, priority 1 (high)

#557 Implement a better method for generating svg images with TikZImage.pm.
  lib/TikZImage.pm
  lib/WeBWorK/PG/IO.pm
  lib/WeBWorK/PG/Translator.pm
  macros/PGbasicmacros.pl
  macros/PGtikz.pl
Labels: Put comment in release notes
